'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright');
test('site pause persists and queues reversible lifecycle work without overriding explicit disable',async t=>{
  const browser=await chromium.launch();t.after(()=>browser.close());const page=await browser.newPage();
  await page.route('https://fixture.test/**',route=>route.fulfill({body:'<!doctype html><html><body>Fixture</body></html>',contentType:'text/html'}));await page.goto('https://fixture.test/');
  const bundle=fs.readFileSync(path.join(__dirname,'../dist/exp-core.js'),'utf8');await page.addScriptTag({content:`(()=>{${bundle};window.core=ExtraPotionsCore;})();`});
  const value=await page.evaluate(async()=>{const calls=[];const product=core.createLifecycle().register({id:'fixture',version:'1.0.0',capabilities:[]},{initialize(){},enable(){calls.push('enable');},disable(){calls.push('disable');}});await product.initialize();await product.enable();core.setSuiteSitePaused(true);await new Promise(resolve=>setTimeout(resolve,30));const paused=product.state;core.setSuiteSitePaused(false);await new Promise(resolve=>setTimeout(resolve,30));const resumed=product.state;await product.disable();core.setSuiteSitePaused(true);core.setSuiteSitePaused(false);await new Promise(resolve=>setTimeout(resolve,30));const explicitlyDisabled=product.state;core.setSuiteSitePaused(true);const card=core.createSuiteSiteControls();document.body.append(card);return{paused,resumed,explicitlyDisabled,calls,checked:card.querySelector('[role="switch"]').getAttribute('aria-checked'),stored:localStorage.getItem('exp:v3:suite-site-pause:fixture.test')};});
  assert.deepEqual(value,{paused:'disabled',resumed:'enabled',explicitlyDisabled:'disabled',calls:['enable','disable','enable','disable'],checked:'true',stored:'1'});
});

test('temporary pause expires but an older timer cannot cancel a replacement persistent pause',async t=>{const browser=await chromium.launch();t.after(()=>browser.close());const page=await browser.newPage();await page.route('https://fixture.test/**',r=>r.fulfill({body:'<html><body>Fixture</body></html>',contentType:'text/html'}));await page.goto('https://fixture.test/');const bundle=fs.readFileSync(path.join(__dirname,'../dist/exp-core.js'),'utf8');await page.addScriptTag({content:`(()=>{${bundle};window.core=ExtraPotionsCore;})();`});await page.evaluate(()=>core.setSuiteSitePaused(true,location.hostname,.001));await page.waitForFunction(()=>!core.suiteSitePaused());assert.equal(await page.evaluate(()=>localStorage.getItem('exp:v3:suite-site-pause:fixture.test')),null);await page.evaluate(()=>core.setSuiteSitePaused(true,location.hostname,.001));await page.addScriptTag({content:`(()=>{${bundle};window.second=ExtraPotionsCore;})();`});await page.evaluate(()=>second.setSuiteSitePaused(true));await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>core.suiteSitePaused()),true);});
