'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const workspace=process.env.EXP_SUITE_ROOT||path.join(__dirname,'../..');
function load(repo,file,context){const text=fs.readFileSync(path.join(workspace,repo,file),'utf8');const match=/  function systemHealthSnapshot\(\) \{[\s\S]*?\n  \}/.exec(text);assert.ok(match,repo+' has product-owned health');vm.runInNewContext(match[0]+';this.health=systemHealthSnapshot;',context);return context.health;}
const available=['WARD','PRISMA','SHIFT','Dropper'].every(repo=>fs.existsSync(path.join(workspace,repo,'src')));const consumerTest=(name,fn)=>test(name,{skip:!available},fn);
function context(){return {Date,ExtraPotionsCore:{suiteSitePaused:()=>false},EXP:{Settings:{snapshot:()=>({}),effective:()=>({})},Engine:{diagnostics:()=>({adapter:{health:'inactive'},coupon:{}}),snapshot:()=>({status:'ready',total:0}),health:()=>({mode:'original',liveResolver:{}})},Retailer:{enabled:()=>true}},settings:{},readRoutingControllerSession:()=>({state:'verify-stream'}),streamEarningHealthSnapshot:()=>({creditedRecently:false,earningVerified:false}),recoveryNavigationState:()=>({suspended:false}),viewingIntent:{snapshot:()=>({})},isStream:()=>true,networkState:{},currentDrop:{},lastGqlSuccessAt:123,requestGqlPoll:()=>{},storageAccountLogin:()=> 'test'};}
consumerTest('WARD unsupported coverage waits and quarantine needs attention',()=>{const c=context(),h=load('WARD','src/ui.js',c);assert.equal(h().state,'waiting');c.EXP.Engine.diagnostics=()=>({adapter:{health:'healthy'},coupon:{quarantined:true}});assert.equal(h().state,'attention');c.EXP.Settings.snapshot=()=>({safeMode:true});assert.equal(h().state,'paused');});
consumerTest('PRISMA zero matches is healthy but processing failures require attention',()=>{const c=context(),h=load('PRISMA','src/ui.js',c);assert.equal(h().state,'working');c.EXP.Engine.snapshot=()=>({status:'catalog-invalid',total:0});assert.equal(h().state,'attention');c.EXP.Settings.snapshot=()=>({safeMode:true});assert.equal(h().state,'paused');});
consumerTest('SHIFT Original is healthy and site pause overrides recovery failure',()=>{const c=context(),h=load('SHIFT','src/ui.js',c);assert.equal(h().state,'working');c.EXP.Engine.health=()=>({liveResolver:{recovery:{suspended:true}}});assert.equal(h().state,'attention');c.ExtraPotionsCore.suiteSitePaused=()=>true;assert.equal(h().state,'paused');});
consumerTest('Dropper campaign verification never promises Twitch credited minutes',()=>{const c=context(),h=load('Dropper','src/parts/07-markup-lists-and-appearance.js',c);assert.equal(h().state,'waiting');assert.match(h().reason,/Twitch|campaign/i);c.streamEarningHealthSnapshot=()=>({creditedRecently:true});assert.equal(h().state,'working');c.ExtraPotionsCore.suiteSitePaused=()=>true;assert.equal(h().state,'paused');});
