'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const consumers=require('../scripts/consumer-roots.cjs').resolveConsumerRoots();
function load(repo,file,context){const text=fs.readFileSync(consumers.file(repo,file),'utf8');const match=/  function systemHealthSnapshot\(\) \{[\s\S]*?\n  \}/.exec(text);assert.ok(match,repo+' has product-owned health');vm.runInNewContext(match[0]+';this.health=systemHealthSnapshot;',context);return context.health;}
const sourceOptions=consumers.options(undefined,'src');const consumerTest=(name,fn)=>test(name,sourceOptions,fn);
function context(){return {Date,ExtraPotionsCore:{suiteSitePaused:()=>false},EXP:{Settings:{snapshot:()=>({}),effective:()=>({})},Engine:{diagnostics:()=>({adapter:{health:'inactive'},coupon:{}}),snapshot:()=>({status:'ready',total:0}),health:()=>({mode:'Original',liveResolver:{}})},Retailer:{enabled:()=>true}},settings:{},readRoutingControllerSession:()=>({state:'verify-stream'}),streamEarningHealthSnapshot:()=>({creditedRecently:false,earningVerified:false}),recoveryNavigationState:()=>({suspended:false}),viewingIntent:{snapshot:()=>({})},isStream:()=>true,networkState:{},currentDrop:{},lastGqlSuccessAt:123,requestGqlPoll:()=>{},storageAccountLogin:()=> 'test'};}
consumerTest('WARD unsupported coverage waits and quarantine needs attention',()=>{const c=context(),h=load('WARD','src/ui.js',c);assert.equal(h().state,'waiting');c.EXP.Engine.diagnostics=()=>({adapter:{health:'healthy'},coupon:{quarantined:true}});assert.equal(h().state,'attention');c.EXP.Settings.snapshot=()=>({safeMode:true});assert.equal(h().state,'paused');});
consumerTest('PRISMA zero matches is healthy but processing failures require attention',()=>{const c=context(),h=load('PRISMA','src/ui.js',c);assert.equal(h().state,'working');c.EXP.Engine.snapshot=()=>({status:'catalog-invalid',total:0});assert.equal(h().state,'attention');c.EXP.Settings.snapshot=()=>({safeMode:true});assert.equal(h().state,'paused');});
consumerTest('SHIFT Original is healthy and site pause overrides recovery failure',()=>{const c=context(),h=load('SHIFT','src/ui.js',c);assert.equal(h().state,'working');c.EXP.Engine.health=()=>({liveResolver:{recovery:{suspended:true}}});assert.equal(h().state,'attention');c.ExtraPotionsCore.suiteSitePaused=()=>true;assert.equal(h().state,'paused');});
consumerTest('Dropper campaign verification never promises Twitch credited minutes',()=>{const c=context(),h=load('Dropper','src/parts/07-markup-lists-and-appearance.js',c);assert.equal(h().state,'waiting');assert.match(h().reason,/Twitch|campaign/i);c.streamEarningHealthSnapshot=()=>({creditedRecently:true,earningVerified:false,login:'stream'});assert.equal(h().state,'waiting');c.streamEarningHealthSnapshot=()=>({creditedRecently:true,earningVerified:true,login:'stream'});assert.equal(h().state,'working');c.ExtraPotionsCore.suiteSitePaused=()=>true;assert.equal(h().state,'paused');});

consumerTest('WARD failed coupon needs attention but disabled retailer takes pause precedence',()=>{const c=context(),h=load('WARD','src/ui.js',c);c.EXP.Engine.diagnostics=()=>({adapter:{health:'healthy'},coupon:{state:'attention',reason:'No confirmation'}});assert.equal(h().state,'attention');c.EXP.Engine.diagnostics=()=>({adapter:{health:'healthy'},recovery:{suspended:true},coupon:{}});c.EXP.Retailer.enabled=()=>false;assert.equal(h().state,'paused');});
consumerTest('SHIFT excluded pages wait and Original and degraded adapters report honest facts',()=>{const c=context(),h=load('SHIFT','src/ui.js',c);c.EXP.Adapters={health:()=>({state:'healthy'})};c.EXP.Engine.health=()=>({mode:'Excluded',liveResolver:{}});assert.equal(h().state,'waiting');c.EXP.Engine.health=()=>({mode:'Original',liveResolver:{}});assert.match(h().reason,/Original/);c.EXP.Engine.health=()=>({mode:'Enhanced',liveResolver:{}});c.EXP.Adapters.health=()=>({state:'degraded',reason:'ADAPTER_PROCESSING'});assert.equal(h().state,'attention');});
